[features]
resolution = true
skip-lint = false

[programs.devnet]
escrow_vault = "a7GxwYc2RSZgiHc9Z8YMr82NppshTNPbqMbfSfvyroE"
premarket_trade = "Amj2QtxyLr6GMgBzN2pB5qaq5V8J7jTBrqc4Ar7y4G5t"
user_profile = "11111111111111111111111111111112"

[programs.testnet]
escrow_vault = "a7GxwYc2RSZgiHc9Z8YMr82NppshTNPbqMbfSfvyroE"
premarket_trade = "Amj2QtxyLr6GMgBzN2pB5qaq5V8J7jTBrqc4Ar7y4G5t"
user_profile = "11111111111111111111111111111112"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/andrein/.config/solana/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
